import express from 'express';
import session from 'express-session';
import bodyParser from 'body-parser';
import fs from 'fs';
import path from 'path';

import { WebSocketServer } from 'ws';
import { URL } from 'url';
import { spawn } from 'child_process';
import NodeMediaServer from 'node-media-server';

const app = express();

const AUTH_PORT = 3000;
const AUTH_IP = 'localhost';

const REC_PORT = 3001;
const REC_IP = 'localhost';

const RTMP_PORT = 1935;
const RTMP_IP = 'localhost';

const KEYS_DIR = path.resolve('../keys'); //path to HLS keys, HLS keys are OFF (plus HLS stream is not generated by NGINX - so it is kind of pointless)

const OUTPUT_DIR = path.resolve('recordings');  //don't touch

var clients_number = 0;

//users
const USERS = { 'student1': 'student1',
                'student2': 'student2',
                'student3': 'student3',
                'student4': 'student4',
                'student5': 'student5',
                'student6': 'student6'
                                    };

app.use(bodyParser.json());

//CORS and headers
app.use((req, res, next) => {
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
    res.header('Access-Control-Allow-Headers', 'Content-Type');
    res.header('Access-Control-Allow-Credentials', 'true');
    
    if (req.url.includes('.m3u8') || req.url.includes('.ts')) {
        res.header('Cache-Control', 'no-cache, no-store, must-revalidate');
        res.header('Pragma', 'no-cache');
        res.header('Expires', '0');
    }
    
    if (req.method === 'OPTIONS') {
        return res.sendStatus(200);
    }
    next();
});

app.use(session({
    secret: 'TajnyKlicProSession',
    resave: false,
    saveUninitialized: false,
    cookie: { httpOnly: true, maxAge: 60 * 60 * 1000 }
}));


//login
app.post('/login', (req, res) => {
    const { username, password } = req.body;
    if (USERS[username] && USERS[username] === password) {
        req.session.user = username;
        res.json({ success: true });
    } else {
        res.status(401).json({ success: false, message: 'Bad credentials' });
    }
});

app.post('/logout', (req, res) => {
    req.session.destroy(() => res.json({ success: true }));
});

//key distribution
app.get('/keys/:name', (req, res) => {
    if (!req.session.user) {
        res.status(403).send('Not logged in');
        return;
    }

    const keyName = path.basename(req.params.name);
    const keyPath = path.join(KEYS_DIR, keyName);

    if (!fs.existsSync(keyPath)) {
        res.status(404).send('Key not found');
        return;
    }

    const data = fs.readFileSync(keyPath);
    res.set('Content-Type', 'application/octet-stream');
    res.send(data);
});
app.use('/recordings', express.static(OUTPUT_DIR));

//Node Media Server setup
const nms = new NodeMediaServer({
  rtmp: {
    port: RTMP_PORT,
    chunk_size: 60000,
    gop_cache: false,
    ping: 30,
    ping_timeout: 60
  },
  http: {
    port: 8000,
    allow_origin: '*'
  }
});

//NMS run
nms.run();
console.log(`RTMP server running on port ${RTMP_PORT}`);

// Auth server run
app.listen(AUTH_PORT, AUTH_IP, () => console.log(`Auth server running on: http://${AUTH_IP}:${AUTH_PORT}`));

//recording code
//-------------------------------------------------------------------------------------------

if (!fs.existsSync(OUTPUT_DIR)) fs.mkdirSync(OUTPUT_DIR);

const wss = new WebSocketServer({ port: REC_PORT });
const clients = new Map();
let combinedFfmpeg = null; 
let connectedClients = [];

wss.on('connection', (ws, req) => {
  const authHandler = (msg, isBinary) => {
    if (isBinary) return;

    try {
      const data = JSON.parse(msg.toString());
      if (data.type === "auth") {
        ws.clientId = data.token_node;
        const clientId = ws.clientId;
        console.log(`Client connected: ${clientId}`);
        clients_number += 1;
        connectedClients.push(clientId); 
        console.log(`Current number of clients: ${clients_number}`);
        console.log(`Connected clients: ${connectedClients.join(', ')}`);

        if (clients_number === 1) { //start for one client
          
          setTimeout(() => {  //delay to stabilize client RTMP stream (caused issues if started immediately)
            if (clients_number !== 1 || connectedClients.length !== 1) {    //just in case somebody disconnects during the cooldown (again caused issues)
              console.log("Client count changed during timeout, skipping single stream start");
              return;
            }
            
            console.log(`Starting single stream for ${connectedClients[0]}...`);  //logging for debugging
            
            const firstClientStream = `rtmp://${RTMP_IP}:${RTMP_PORT}/live/${connectedClients[0]}`;
            console.log(`Source stream: ${firstClientStream}`);
            
            combinedFfmpeg = spawn('ffmpeg', [  //only for one client (with 4 different qualities)
              '-i', firstClientStream,
              '-filter_complex',
              '[0:v]format=yuv420p,fps=25,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text=\'' + connectedClients[0] + '\':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[base];' +
              '[base]split=4[v1080s][v720s][v480s][v360s];' +
              '[v1080s]scale=1920:1080:force_original_aspect_ratio=decrease:flags=bicubic,pad=1920:1080:(ow-iw)/2:(oh-ih)/2:color=black[src];' +
              '[v720s]scale=1280:720:force_original_aspect_ratio=decrease:flags=bicubic,pad=1280:720:(ow-iw)/2:(oh-ih)/2:color=black[v1];' +
              '[v480s]scale=854:480:force_original_aspect_ratio=decrease:flags=bicubic,pad=854:480:(ow-iw)/2:(oh-ih)/2:color=black[v2];' +
              '[v360s]scale=640:360:force_original_aspect_ratio=decrease:flags=bicubic,pad=640:360:(ow-iw)/2:(oh-ih)/2:color=black[v3]',
              //1080p
              '-map', '[src]',
              '-c:v', 'libx264',
              '-preset', 'veryfast',
              '-tune', 'zerolatency',
              '-b:v', '4000k',
              '-maxrate', '4200k',
              '-bufsize', '8400k',
              '-g', '50',
              '-keyint_min', '25',
              '-profile:v', 'high',
              //720p
              '-map', '[v1]',
              '-c:v', 'libx264',
              '-preset', 'veryfast',
              '-tune', 'zerolatency',
              '-b:v', '2500k',
              '-maxrate', '2650k',
              '-bufsize', '5000k',
              '-g', '50',
              '-keyint_min', '25',
              '-profile:v', 'high',
              //480p
              '-map', '[v2]',
              '-c:v', 'libx264',
              '-preset', 'veryfast',
              '-tune', 'zerolatency',
              '-b:v', '1200k',
              '-maxrate', '1300k',
              '-bufsize', '2400k',
              '-g', '50',
              '-keyint_min', '25',
              '-profile:v', 'main',
              //360p
              '-map', '[v3]',
              '-c:v', 'libx264',
              '-preset', 'veryfast',
              '-tune', 'zerolatency',
              '-b:v', '800k',
              '-maxrate', '900k',
              '-bufsize', '1600k',
              '-g', '50',
              '-keyint_min', '25',
              '-profile:v', 'main',
              //audio
              '-map', 'a:0', '-c:a', 'aac', '-b:a', '128k', '-ac', '2', '-ar', '48000',
              '-map', 'a:0', '-c:a', 'aac', '-b:a', '128k', '-ac', '2', '-ar', '48000',
              '-map', 'a:0', '-c:a', 'aac', '-b:a', '96k', '-ac', '2', '-ar', '48000',
              '-map', 'a:0', '-c:a', 'aac', '-b:a', '96k', '-ac', '2', '-ar', '48000',
              //rest of HLS tags
              '-f', 'hls',
              '-hls_time', '1',
              '-hls_list_size', '3',
              '-hls_flags', 'independent_segments+delete_segments+omit_endlist',
              '-hls_segment_type', 'mpegts',
              '-hls_segment_filename', path.join(OUTPUT_DIR, 'stream_%v', 'segment%03d.ts'),
              '-master_pl_name', 'combined.m3u8',
              '-var_stream_map', 'v:0,a:0 v:1,a:1 v:2,a:2 v:3,a:3',
              path.join(OUTPUT_DIR, 'stream_%v', 'playlist.m3u8')
            ]);
            
            ['0', '1', '2', '3'].forEach(v => { //this creates folders for each quality
              const dir = path.join(OUTPUT_DIR, `stream_${v}`);
              if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
            });

            combinedFfmpeg.stdout.on('data', data => console.log(`Combined FFmpeg (copy) stdout: ${data}`));
            combinedFfmpeg.stderr.on('data', data => console.log(`Combined FFmpeg (copy): ${data}`));
            combinedFfmpeg.on('close', code => {
              console.log(`Combined FFmpeg (copy) process exited with ${code}`);    //logging for debugging
              combinedFfmpeg = null;
            });
            combinedFfmpeg.on('error', (err) => {
              console.error(`Combined FFmpeg (copy) process error:`, err);          //logging for debugging
            });
          }, 3000); //this is the set delay before the combined stream starts (as mentioned above) (3000 = 3s)
        } else {  //now code for two or more clients (since it needs complex_filters, it is separate)
          console.log(`${clients_number} clients connected. Waiting for streams to initialize...`);
          
          setTimeout(() => {  //again this is timeout for the client stream(s) to start properly (again caused issues)

            if (connectedClients.length < 2) {    //in case somebody disconnects during the cooldown (same as for one client)
              console.log("Not enough clients, skipping grid layout");
              return;
            }
            
            console.log(`Starting combined stream grid with ${connectedClients.length} clients: ${connectedClients.join(', ')}`);   //logging for debugging (again)
            
            if (combinedFfmpeg) { //hardkill if there is some process running (just in case something goes wrong)
              console.log("Stopping existing combined stream...");
              combinedFfmpeg.kill('SIGTERM');
              
              setTimeout(() => { //timeout for the process to be killed properly (once again caused issues)
                startGridLayout();
              }, 1000);
            } else {
              startGridLayout();
            }
            
            function startGridLayout() {
              try { //cleaning of old files
                const files = fs.readdirSync(OUTPUT_DIR);
                files.forEach(file => {
                  if (file.startsWith('combined_') && (file.endsWith('.ts') || file.endsWith('.m3u8'))) {
                    fs.unlinkSync(path.join(OUTPUT_DIR, file));
                  }
                });
              } catch (err) {
                console.error('Error cleaning up combined files:', err);
              }
              
              const ffmpegArgs = [];
              
              connectedClients.forEach(clientId => {  //loop to add every active client as ffmpeg input
                ffmpegArgs.push(
                  '-i', `rtmp://${RTMP_IP}:${RTMP_PORT}/live/${clientId}`
                );
              });
              
              let filterComplex = '';
              let audioMerge = '';
              const numClients = connectedClients.length;
              
              //grid filters for each number of clients
              if (numClients === 2) {
                //side by side grid
                filterComplex += `[0:v]setpts=PTS-STARTPTS,scale=960:1080:force_original_aspect_ratio=decrease,pad=960:1080:-1:-1:color=black,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[0]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v0];`;
                filterComplex += `[1:v]setpts=PTS-STARTPTS,scale=960:1080:force_original_aspect_ratio=decrease,pad=960:1080:-1:-1:color=black,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[1]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v1];`;
                filterComplex += `[v0][v1]xstack=inputs=2:layout=0_0|w0_0[v]`;
              } else if (numClients === 3) {
                //one top middle, two below (sort of triangle)
                filterComplex += `[0:v]setpts=PTS-STARTPTS,scale=1920:540:force_original_aspect_ratio=decrease,pad=1920:540:-1:-1:color=black,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[0]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v0];`;
                filterComplex += `[1:v]setpts=PTS-STARTPTS,scale=960:540:force_original_aspect_ratio=decrease,pad=960:540:-1:-1:color=black,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[1]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v1];`;
                filterComplex += `[2:v]setpts=PTS-STARTPTS,scale=960:540:force_original_aspect_ratio=decrease,pad=960:540:-1:-1:color=black,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[2]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v2];`;
                filterComplex += `[v1][v2]xstack=inputs=2:layout=0_0|w0_0[row1];`;
                filterComplex += `[v0][row1]xstack=inputs=2:layout=0_0|0_h0[v]`;
              } else if (numClients === 4) {
                //2x2 grid
                filterComplex += `[0:v]setpts=PTS-STARTPTS,scale=960:540:force_original_aspect_ratio=increase,crop=960:540,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[0]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v0];`;
                filterComplex += `[1:v]setpts=PTS-STARTPTS,scale=960:540:force_original_aspect_ratio=increase,crop=960:540,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[1]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v1];`;
                filterComplex += `[2:v]setpts=PTS-STARTPTS,scale=960:540:force_original_aspect_ratio=increase,crop=960:540,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[2]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v2];`;
                filterComplex += `[3:v]setpts=PTS-STARTPTS,scale=960:540:force_original_aspect_ratio=increase,crop=960:540,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[3]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v3];`;
                filterComplex += `[v0][v1]xstack=inputs=2:layout=0_0|w0_0[row0];`;
                filterComplex += `[v2][v3]xstack=inputs=2:layout=0_0|w0_0[row1];`;
                filterComplex += `[row0][row1]xstack=inputs=2:layout=0_0|0_h0[v]`;
              } else if (numClients === 5) {
                //two on top, three below (cropped to fit)
                filterComplex += `[0:v]setpts=PTS-STARTPTS,scale=qhd,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[0]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v0];`;
                filterComplex += `[1:v]setpts=PTS-STARTPTS,scale=qhd,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[1]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v1];`;
                filterComplex += `[2:v]setpts=PTS-STARTPTS,scale=640:540:force_original_aspect_ratio=increase,crop=640:540,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[2]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v2];`;
                filterComplex += `[3:v]setpts=PTS-STARTPTS,scale=640:540:force_original_aspect_ratio=increase,crop=640:540,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[3]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v3];`;
                filterComplex += `[4:v]setpts=PTS-STARTPTS,scale=640:540:force_original_aspect_ratio=increase,crop=640:540,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[4]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v4];`;
                filterComplex += `[v0][v1]xstack=inputs=2:layout=0_0|w0_0[row0];`;
                filterComplex += `[v2][v3][v4]xstack=inputs=3:layout=0_0|w0_0|w0+w1_0[row1];`;
                filterComplex += `[row0][row1]xstack=inputs=2:layout=0_0|0_h0:fill=black[v]`;
              } else if (numClients === 6) {
                //3x2 grid
                filterComplex += `[0:v]setpts=PTS-STARTPTS,scale=640:540:force_original_aspect_ratio=increase,crop=640:540,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[0]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v0];`;
                filterComplex += `[1:v]setpts=PTS-STARTPTS,scale=640:540:force_original_aspect_ratio=increase,crop=640:540,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[1]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v1];`;
                filterComplex += `[2:v]setpts=PTS-STARTPTS,scale=640:540:force_original_aspect_ratio=increase,crop=640:540,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[2]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v2];`;
                filterComplex += `[3:v]setpts=PTS-STARTPTS,scale=640:540:force_original_aspect_ratio=increase,crop=640:540,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[3]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v3];`;
                filterComplex += `[4:v]setpts=PTS-STARTPTS,scale=640:540:force_original_aspect_ratio=increase,crop=640:540,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[4]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v4];`;
                filterComplex += `[5:v]setpts=PTS-STARTPTS,scale=640:540:force_original_aspect_ratio=increase,crop=640:540,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[5]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v5];`;
                filterComplex += `[v0][v1][v2]xstack=inputs=3:layout=0_0|w0_0|w0+w1_0[row0];`;
                filterComplex += `[v3][v4][v5]xstack=inputs=3:layout=0_0|w0_0|w0+w1_0[row1];`;
                filterComplex += `[row0][row1]xstack=inputs=2:layout=0_0|0_h0[v]`;
              }
              
              //to merge audio tracks into one
              audioMerge = connectedClients.map((_, i) => `[${i}:a]`).join('');
              audioMerge += `amerge=inputs=${numClients}[amerged];`;
              audioMerge += `[amerged]asplit=4[a0][a1][a2][a3]`;
              
              filterComplex += `;${audioMerge}`;
              
              //split qualities
              filterComplex += `;[v]format=yuv420p,fps=25[base];`;
              filterComplex += `[base]split=4[v1080s][v720s][v480s][v360s];`;
              filterComplex += `[v1080s]scale=1920:1080:force_original_aspect_ratio=decrease:flags=bicubic,pad=1920:1080:(ow-iw)/2:(oh-ih)/2:color=black[src];`;
              filterComplex += `[v720s]scale=1280:720:force_original_aspect_ratio=decrease:flags=bicubic,pad=1280:720:(ow-iw)/2:(oh-ih)/2:color=black[v1];`;
              filterComplex += `[v480s]scale=854:480:force_original_aspect_ratio=decrease:flags=bicubic,pad=854:480:(ow-iw)/2:(oh-ih)/2:color=black[v2];`;
              filterComplex += `[v360s]scale=640:360:force_original_aspect_ratio=decrease:flags=bicubic,pad=640:360:(ow-iw)/2:(oh-ih)/2:color=black[v3]`;
              
              console.log('Filter complex:', filterComplex);
              
              ffmpegArgs.push(    //rest of fmmpeg tags (including them different qualities)
                '-filter_complex', filterComplex,
                //1080p
                '-map', '[src]',
                '-c:v', 'libx264',
                '-preset', 'veryfast',
                '-tune', 'zerolatency',
                '-b:v', '4000k',
                '-maxrate', '4200k',
                '-bufsize', '8400k',
                '-g', '50',
                '-keyint_min', '25',
                '-profile:v', 'high',
                //720p
                '-map', '[v1]',
                '-c:v', 'libx264',
                '-preset', 'veryfast',
                '-tune', 'zerolatency',
                '-b:v', '2500k',
                '-maxrate', '2650k',
                '-bufsize', '5000k',
                '-g', '50',
                '-keyint_min', '25',
                '-profile:v', 'high',
                //480p
                '-map', '[v2]',
                '-c:v', 'libx264',
                '-preset', 'veryfast',
                '-tune', 'zerolatency',
                '-b:v', '1200k',
                '-maxrate', '1300k',
                '-bufsize', '2400k',
                '-g', '50',
                '-keyint_min', '25',
                '-profile:v', 'main',
                //360p
                '-map', '[v3]',
                '-c:v', 'libx264',
                '-preset', 'veryfast',
                '-tune', 'zerolatency',
                '-b:v', '800k',
                '-maxrate', '900k',
                '-bufsize', '1600k',
                '-g', '50',
                '-keyint_min', '25',
                '-profile:v', 'main',
                //audio
                '-map', '[a0]', '-c:a', 'aac', '-b:a', '128k', '-ac', '2', '-ar', '48000',
                '-map', '[a1]', '-c:a', 'aac', '-b:a', '128k', '-ac', '2', '-ar', '48000',
                '-map', '[a2]', '-c:a', 'aac', '-b:a', '96k', '-ac', '2', '-ar', '48000',
                '-map', '[a3]', '-c:a', 'aac', '-b:a', '96k', '-ac', '2', '-ar', '48000',
                //rest of HLS tags
                '-f', 'hls',
                '-hls_time', '1',
                '-hls_list_size', '3',
                '-hls_flags', 'independent_segments+delete_segments+omit_endlist',
                '-hls_segment_type', 'mpegts',
                '-hls_segment_filename', path.join(OUTPUT_DIR, 'stream_%v', 'segment%03d.ts'),
                '-master_pl_name', 'combined.m3u8',
                '-var_stream_map', 'v:0,a:0 v:1,a:1 v:2,a:2 v:3,a:3',
                path.join(OUTPUT_DIR, 'stream_%v', 'playlist.m3u8')
              );
              
              ['0', '1', '2', '3'].forEach(v => {   //once again, creates folders for each quality  (same as for one client)
                const dir = path.join(OUTPUT_DIR, `stream_${v}`);
                if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
              });
              
              console.log('Starting ffmpeg with grid layout...');
              combinedFfmpeg = spawn('ffmpeg', ffmpegArgs);

              combinedFfmpeg.stderr.on('data', data => console.log(`Combined FFmpeg: ${data}`));    //for debugging
              combinedFfmpeg.on('close', code => {
                console.log(`Combined FFmpeg process exited with ${code}`);   //for debugging
                combinedFfmpeg = null;
              });
              combinedFfmpeg.on('error', (err) => {
                console.error(`Combined FFmpeg process error:`, err);   //for debugging
              });
            }
          }, 2000); //once to set the actual time delay (2000 = 2s)
        }

        const ffmpeg = spawn('ffmpeg', [      //this is ffmpeg that creates RTMP streams for each client
          '-f', 'webm',
          '-i', 'pipe:0',
          '-c:v', 'libx264',
          '-preset', 'ultrafast',
          '-tune', 'zerolatency',
          '-g', '15',
          '-keyint_min', '15',
          '-sc_threshold', '0',
          '-c:a', 'aac',
          '-b:a', '128k',
          '-ar', '48000',
          '-f', 'flv',
          '-flvflags', 'no_duration_filesize',
          `rtmp://${RTMP_IP}:${RTMP_PORT}/live/${clientId}`
        ]);

        ffmpeg.on('error', (err) => {
          console.error(`FFmpeg process error for ${clientId}:`, err);      //for debugging
        });

        ffmpeg.stderr.on('data', data => console.log(`FFmpeg (${clientId}): ${data}`));     //for debugging
        ffmpeg.on('close', code => console.log(`FFmpeg process for ${clientId} exited with ${code}`));    //for debugging

        clients.set(clientId, { ws, ffmpeg });

        ws.off('message', authHandler);

        ws.on('message', (chunk, isBinary) => {   //adds binary data (video/audio) to ffmpeg internal pipe
          if (isBinary || chunk instanceof Buffer || chunk instanceof ArrayBuffer) {
            ffmpeg.stdin.write(Buffer.from(chunk));
          }
        });

        ws.on('close', () => {
          console.log(`Client disconnected: ${clientId}`);
          ffmpeg.stdin.end();
          clients.delete(clientId);
          clients_number -= 1;
          
          connectedClients = connectedClients.filter(id => id !== clientId);
          console.log(`Current number of clients: ${clients_number}`);
          console.log(`Remaining clients: ${connectedClients.join(', ')}`);

          switch (clients_number) {   //this handles starting/stopping combined ffmpeg when client(s) disconnect(s)
            case 0:
              if (combinedFfmpeg) {
                console.log("No clients remaining. Stopping combined stream...");     //logs for debugging
                try {
                  combinedFfmpeg.kill('SIGKILL');
                  combinedFfmpeg = null;
                } catch (err) {
                  console.error("Error killing combined ffmpeg:", err);     //again
                }
              }
              break;
            
            case 1:       //i don't think I have to explain this again (it is almost the same as when clients connect)
              if (combinedFfmpeg) {
                console.log(`Only 1 client remaining (${connectedClients[0]}). Restarting with single stream copy...`);     //logs for debugging
                try {
                  combinedFfmpeg.kill('SIGKILL');
                } catch (err) {
                  console.error("Error killing combined ffmpeg:", err);
                }
                combinedFfmpeg = null;
              }
              
              setTimeout(() => {
                if (clients_number !== 1 || connectedClients.length !== 1) {
                  console.log(`Client count changed during timeout, skipping restart (clients_number: ${clients_number}, connectedClients: ${connectedClients.length})`);
                  return;
                }
                
                console.log("Cleaning up old combined segments...");
                
                try {
                  const files = fs.readdirSync(OUTPUT_DIR);
                  files.forEach(file => {
                    if (file.startsWith('combined_') && (file.endsWith('.ts') || file.endsWith('.m3u8'))) {
                      fs.unlinkSync(path.join(OUTPUT_DIR, file));
                    }
                  });
                } catch (err) {
                  console.error('Error cleaning up combined files:', err);
                }
                
                console.log(`Starting single stream with adaptive bitrate for ${connectedClients[0]}...`);
                
                const remainingClientStream = `rtmp://${RTMP_IP}:${RTMP_PORT}/live/${connectedClients[0]}`;
                
                combinedFfmpeg = spawn('ffmpeg', [
                  '-i', remainingClientStream,
                  '-filter_complex',
                  '[0:v]format=yuv420p,fps=25,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text=\'' + connectedClients[0] + '\':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[base];' +
                  '[base]split=4[v1080s][v720s][v480s][v360s];' +
                  '[v1080s]scale=1920:1080:force_original_aspect_ratio=decrease:flags=bicubic,pad=1920:1080:(ow-iw)/2:(oh-ih)/2:color=black[src];' +
                  '[v720s]scale=1280:720:force_original_aspect_ratio=decrease:flags=bicubic,pad=1280:720:(ow-iw)/2:(oh-ih)/2:color=black[v1];' +
                  '[v480s]scale=854:480:force_original_aspect_ratio=decrease:flags=bicubic,pad=854:480:(ow-iw)/2:(oh-ih)/2:color=black[v2];' +
                  '[v360s]scale=640:360:force_original_aspect_ratio=decrease:flags=bicubic,pad=640:360:(ow-iw)/2:(oh-ih)/2:color=black[v3]',
                  //1080p
                  '-map', '[src]',
                  '-c:v', 'libx264',
                  '-preset', 'veryfast',
                  '-tune', 'zerolatency',
                  '-b:v', '4000k',
                  '-maxrate', '4200k',
                  '-bufsize', '8400k',
                  '-g', '50',
                  '-keyint_min', '25',
                  '-profile:v', 'high',
                  //720p
                  '-map', '[v1]',
                  '-c:v', 'libx264',
                  '-preset', 'veryfast',
                  '-tune', 'zerolatency',
                  '-b:v', '2500k',
                  '-maxrate', '2650k',
                  '-bufsize', '5000k',
                  '-g', '50',
                  '-keyint_min', '25',
                  '-profile:v', 'high',
                  //480p
                  '-map', '[v2]',
                  '-c:v', 'libx264',
                  '-preset', 'veryfast',
                  '-tune', 'zerolatency',
                  '-b:v', '1200k',
                  '-maxrate', '1300k',
                  '-bufsize', '2400k',
                  '-g', '50',
                  '-keyint_min', '25',
                  '-profile:v', 'main',
                  //360p
                  '-map', '[v3]',
                  '-c:v', 'libx264',
                  '-preset', 'veryfast',
                  '-tune', 'zerolatency',
                  '-b:v', '800k',
                  '-maxrate', '900k',
                  '-bufsize', '1600k',
                  '-g', '50',
                  '-keyint_min', '25',
                  '-profile:v', 'main',
                  //audio
                  '-map', 'a:0', '-c:a', 'aac', '-b:a', '128k', '-ac', '2', '-ar', '48000',
                  '-map', 'a:0', '-c:a', 'aac', '-b:a', '128k', '-ac', '2', '-ar', '48000',
                  '-map', 'a:0', '-c:a', 'aac', '-b:a', '96k', '-ac', '2', '-ar', '48000',
                  '-map', 'a:0', '-c:a', 'aac', '-b:a', '96k', '-ac', '2', '-ar', '48000',
                  //rest of HLS tags
                  '-f', 'hls',
                  '-hls_time', '1',
                  '-hls_list_size', '3',
                  '-hls_flags', 'independent_segments+delete_segments+omit_endlist',
                  '-hls_segment_type', 'mpegts',
                  '-hls_segment_filename', path.join(OUTPUT_DIR, 'stream_%v', 'segment%03d.ts'),
                  '-master_pl_name', 'combined.m3u8',
                  '-var_stream_map', 'v:0,a:0 v:1,a:1 v:2,a:2 v:3,a:3',
                  path.join(OUTPUT_DIR, 'stream_%v', 'playlist.m3u8')
                ]);
                
                ['0', '1', '2', '3'].forEach(v => {
                  const dir = path.join(OUTPUT_DIR, `stream_${v}`);
                  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
                });

                combinedFfmpeg.stderr.on('data', data => console.log(`Combined FFmpeg (copy): ${data}`));
                combinedFfmpeg.on('close', code => {
                  console.log(`Combined FFmpeg (copy) process exited with ${code}`);
                  combinedFfmpeg = null;
                });
                combinedFfmpeg.on('error', (err) => {
                  console.error(`Combined FFmpeg (copy) process error:`, err);
                });
              }, 4000);
              break;
            
            default:
              if (combinedFfmpeg && clients_number >= 2) {
                console.log(`${clients_number} clients remaining. Restarting grid layout...`);
                try {
                  combinedFfmpeg.kill('SIGKILL');
                } catch (err) {
                  console.error("Error killing combined ffmpeg:", err);
                }
                combinedFfmpeg = null;
              }
              
              if (clients_number >= 2) {
                setTimeout(() => {
                  if (clients_number < 2 || connectedClients.length < 2) {
                    console.log(`Not enough clients during timeout, skipping grid restart (clients_number: ${clients_number}, connectedClients: ${connectedClients.length})`);
                    return;
                  }
                  
                  console.log("Cleaning up old combined segments...");
      
                  try {
                    const files = fs.readdirSync(OUTPUT_DIR);
                    files.forEach(file => {
                      if (file.startsWith('combined_') && (file.endsWith('.ts') || file.endsWith('.m3u8'))) {
                        fs.unlinkSync(path.join(OUTPUT_DIR, file));
                      }
                    });
                  } catch (err) {
                    console.error('Error cleaning up combined files:', err);
                  }
                
                  console.log(`Restarting combined stream grid with ${connectedClients.length} clients: ${connectedClients.join(', ')}`);
                  
                  const ffmpegArgs = [];
                  
                  connectedClients.forEach(clientId => {
                    ffmpegArgs.push(
                      '-i', `rtmp://${RTMP_IP}:${RTMP_PORT}/live/${clientId}`
                    );
                  });
                  
                  let filterComplex = '';
                  let audioMerge = '';
                  const numClients = connectedClients.length;

                if (numClients === 2) {
                //side by side grid
                filterComplex += `[0:v]setpts=PTS-STARTPTS,scale=960:1080:force_original_aspect_ratio=decrease,pad=960:1080:-1:-1:color=black,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[0]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v0];`;
                filterComplex += `[1:v]setpts=PTS-STARTPTS,scale=960:1080:force_original_aspect_ratio=decrease,pad=960:1080:-1:-1:color=black,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[1]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v1];`;
                filterComplex += `[v0][v1]xstack=inputs=2:layout=0_0|w0_0[v]`;
              } else if (numClients === 3) {
                //one top middle, two below (sort of triangle)
                filterComplex += `[0:v]setpts=PTS-STARTPTS,scale=1920:540:force_original_aspect_ratio=decrease,pad=1920:540:-1:-1:color=black,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[0]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v0];`;
                filterComplex += `[1:v]setpts=PTS-STARTPTS,scale=960:540:force_original_aspect_ratio=decrease,pad=960:540:-1:-1:color=black,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[1]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v1];`;
                filterComplex += `[2:v]setpts=PTS-STARTPTS,scale=960:540:force_original_aspect_ratio=decrease,pad=960:540:-1:-1:color=black,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[2]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v2];`;
                filterComplex += `[v1][v2]xstack=inputs=2:layout=0_0|w0_0[row1];`;
                filterComplex += `[v0][row1]xstack=inputs=2:layout=0_0|0_h0[v]`;
              } else if (numClients === 4) {
                //2x2 grid
                filterComplex += `[0:v]setpts=PTS-STARTPTS,scale=960:540:force_original_aspect_ratio=increase,crop=960:540,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[0]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v0];`;
                filterComplex += `[1:v]setpts=PTS-STARTPTS,scale=960:540:force_original_aspect_ratio=increase,crop=960:540,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[1]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v1];`;
                filterComplex += `[2:v]setpts=PTS-STARTPTS,scale=960:540:force_original_aspect_ratio=increase,crop=960:540,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[2]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v2];`;
                filterComplex += `[3:v]setpts=PTS-STARTPTS,scale=960:540:force_original_aspect_ratio=increase,crop=960:540,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[3]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v3];`;
                filterComplex += `[v0][v1]xstack=inputs=2:layout=0_0|w0_0[row0];`;
                filterComplex += `[v2][v3]xstack=inputs=2:layout=0_0|w0_0[row1];`;
                filterComplex += `[row0][row1]xstack=inputs=2:layout=0_0|0_h0[v]`;
              } else if (numClients === 5) {
                //two on top, three below (cropped to fit)
                filterComplex += `[0:v]setpts=PTS-STARTPTS,scale=qhd,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[0]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v0];`;
                filterComplex += `[1:v]setpts=PTS-STARTPTS,scale=qhd,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[1]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v1];`;
                filterComplex += `[2:v]setpts=PTS-STARTPTS,scale=640:540:force_original_aspect_ratio=increase,crop=640:540,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[2]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v2];`;
                filterComplex += `[3:v]setpts=PTS-STARTPTS,scale=640:540:force_original_aspect_ratio=increase,crop=640:540,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[3]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v3];`;
                filterComplex += `[4:v]setpts=PTS-STARTPTS,scale=640:540:force_original_aspect_ratio=increase,crop=640:540,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[4]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v4];`;
                filterComplex += `[v0][v1]xstack=inputs=2:layout=0_0|w0_0[row0];`;
                filterComplex += `[v2][v3][v4]xstack=inputs=3:layout=0_0|w0_0|w0+w1_0[row1];`;
                filterComplex += `[row0][row1]xstack=inputs=2:layout=0_0|0_h0:fill=black[v]`;
              } else if (numClients === 6) {
                //3x2 grid
                filterComplex += `[0:v]setpts=PTS-STARTPTS,scale=640:540:force_original_aspect_ratio=increase,crop=640:540,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[0]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v0];`;
                filterComplex += `[1:v]setpts=PTS-STARTPTS,scale=640:540:force_original_aspect_ratio=increase,crop=640:540,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[1]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v1];`;
                filterComplex += `[2:v]setpts=PTS-STARTPTS,scale=640:540:force_original_aspect_ratio=increase,crop=640:540,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[2]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v2];`;
                filterComplex += `[3:v]setpts=PTS-STARTPTS,scale=640:540:force_original_aspect_ratio=increase,crop=640:540,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[3]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v3];`;
                filterComplex += `[4:v]setpts=PTS-STARTPTS,scale=640:540:force_original_aspect_ratio=increase,crop=640:540,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[4]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v4];`;
                filterComplex += `[5:v]setpts=PTS-STARTPTS,scale=640:540:force_original_aspect_ratio=increase,crop=640:540,drawtext=fontfile=C\\\\:/Windows/Fonts/arial.ttf:text='${connectedClients[5]}':fontcolor=white:fontsize=25:x=(w-text_w-10):y=(h-text_h-10)[v5];`;
                filterComplex += `[v0][v1][v2]xstack=inputs=3:layout=0_0|w0_0|w0+w1_0[row0];`;
                filterComplex += `[v3][v4][v5]xstack=inputs=3:layout=0_0|w0_0|w0+w1_0[row1];`;
                filterComplex += `[row0][row1]xstack=inputs=2:layout=0_0|0_h0[v]`;
              }
                  
                  audioMerge = connectedClients.map((_, i) => `[${i}:a]`).join('');
                  audioMerge += `amerge=inputs=${numClients}[amerged];`;
                  audioMerge += `[amerged]asplit=4[a0][a1][a2][a3]`;
                  filterComplex += `;${audioMerge}`;
                  
                  filterComplex += `;[v]format=yuv420p,fps=25[base];`;
                  filterComplex += `[base]split=4[v1080s][v720s][v480s][v360s];`;
                  filterComplex += `[v1080s]scale=1920:1080:force_original_aspect_ratio=decrease:flags=bicubic,pad=1920:1080:(ow-iw)/2:(oh-ih)/2:color=black[src];`;
                  filterComplex += `[v720s]scale=1280:720:force_original_aspect_ratio=decrease:flags=bicubic,pad=1280:720:(ow-iw)/2:(oh-ih)/2:color=black[v1];`;
                  filterComplex += `[v480s]scale=854:480:force_original_aspect_ratio=decrease:flags=bicubic,pad=854:480:(ow-iw)/2:(oh-ih)/2:color=black[v2];`;
                  filterComplex += `[v360s]scale=640:360:force_original_aspect_ratio=decrease:flags=bicubic,pad=640:360:(ow-iw)/2:(oh-ih)/2:color=black[v3]`;
                  
                  ffmpegArgs.push(
                    '-filter_complex', filterComplex,
                    //1080p
                    '-map', '[src]',
                    '-c:v', 'libx264',
                    '-preset', 'veryfast',
                    '-tune', 'zerolatency',
                    '-b:v', '4000k',
                    '-maxrate', '4200k',
                    '-bufsize', '8400k',
                    '-g', '50',
                    '-keyint_min', '25',
                    '-profile:v', 'high',
                    //720p
                    '-map', '[v1]',
                    '-c:v', 'libx264',
                    '-preset', 'veryfast',
                    '-tune', 'zerolatency',
                    '-b:v', '2500k',
                    '-maxrate', '2650k',
                    '-bufsize', '5000k',
                    '-g', '50',
                    '-keyint_min', '25',
                    '-profile:v', 'high',
                    //480p
                    '-map', '[v2]',
                    '-c:v', 'libx264',
                    '-preset', 'veryfast',
                    '-tune', 'zerolatency',
                    '-b:v', '1200k',
                    '-maxrate', '1300k',
                    '-bufsize', '2400k',
                    '-g', '50',
                    '-keyint_min', '25',
                    '-profile:v', 'main',
                    //360p
                    '-map', '[v3]',
                    '-c:v', 'libx264',
                    '-preset', 'veryfast',
                    '-tune', 'zerolatency',
                    '-b:v', '800k',
                    '-maxrate', '900k',
                    '-bufsize', '1600k',
                    '-g', '50',
                    '-keyint_min', '25',
                    '-profile:v', 'main',
                    //audio
                    '-map', '[a0]', '-c:a', 'aac', '-b:a', '128k', '-ac', '2', '-ar', '48000',
                    '-map', '[a1]', '-c:a', 'aac', '-b:a', '128k', '-ac', '2', '-ar', '48000',
                    '-map', '[a2]', '-c:a', 'aac', '-b:a', '96k', '-ac', '2', '-ar', '48000',
                    '-map', '[a3]', '-c:a', 'aac', '-b:a', '96k', '-ac', '2', '-ar', '48000',
                    //rest of HLS tags
                    '-f', 'hls',
                    '-hls_time', '1',
                    '-hls_list_size', '3',
                    '-hls_flags', 'independent_segments+delete_segments+omit_endlist',
                    '-hls_segment_type', 'mpegts',
                    '-hls_segment_filename', path.join(OUTPUT_DIR, 'stream_%v', 'segment%03d.ts'),
                    '-master_pl_name', 'combined.m3u8',
                    '-var_stream_map', 'v:0,a:0 v:1,a:1 v:2,a:2 v:3,a:3',
                    path.join(OUTPUT_DIR, 'stream_%v', 'playlist.m3u8')
                  );
                  
                  ['0', '1', '2', '3'].forEach(v => {
                    const dir = path.join(OUTPUT_DIR, `stream_${v}`);
                    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
                  });
                  
                  combinedFfmpeg = spawn('ffmpeg', ffmpegArgs);

                  combinedFfmpeg.stderr.on('data', data => console.log(`Combined FFmpeg: ${data}`));
                  combinedFfmpeg.on('close', code => {
                    console.log(`Combined FFmpeg process exited with ${code}`);
                    combinedFfmpeg = null;
                  });
                  combinedFfmpeg.on('error', (err) => {
                    console.error(`Combined FFmpeg process error:`, err);
                  });
                }, 4000);
              }
              break;
          }
        });
      }
    } catch (err) {
      console.error("Invalid JSON message:", err);
    }
  };

  ws.on("message", authHandler);
});

console.log(`WebSocket server running on ws://${REC_IP}:${REC_PORT}`);